export const ICONS = {
  brush_icon: new URL("./Brush.svg",import.meta.url).href,
  eraser_icon: new URL("./Eraser.svg",import.meta.url).href,
  marker_icon: new URL("./Marker.svg",import.meta.url).href,
  eye_icon: new URL("./Eye.svg",import.meta.url).href,
  folder_icon: new URL("./Folder.svg",import.meta.url).href,
  image_icon: new URL("./image.svg",import.meta.url).href,
  check_icon: new URL("./check.svg",import.meta.url).href,
  edit_icon: new URL("./edit.svg",import.meta.url).href,
  blocked_icon: new URL("./blocked.svg",import.meta.url).href,
  redo_icon: new URL("./redo.svg",import.meta.url).href,
  undo_icon: new URL("./undo.svg",import.meta.url).href,
  logo_icon: new URL("./logo.svg",import.meta.url).href,
  plus_icon: new URL("./plus.svg",import.meta.url).href,
  upload_icon: new URL("./upload.svg",import.meta.url).href,
  pencil_icon: new URL("./Pencil.svg",import.meta.url).href,
  bg_image: new URL("./Background.png",import.meta.url).href,
  ab_icon: new URL("./ab.svg",import.meta.url).href,
  ab2_icon: new URL("./ab2.svg",import.meta.url).href,
  na1_icon: new URL("./na1.svg",import.meta.url).href,
  na2_icon: new URL("./na2.svg",import.meta.url).href,
  back_icon: new URL("./back.svg",import.meta.url).href,
  dell_icon: new URL("./dell_icon.png",import.meta.url).href,
  zoom_2x_icon: new URL("./zoom-2x-icon.svg",import.meta.url).href,


  logo: new URL("./images/Logo.png",import.meta.url).href,
  edit_img: new URL("./images/edit-image.svg",import.meta.url).href,
  not_available_image: new URL("./images/not_available-1.png",import.meta.url).href,


  redo: new URL("./icons/redo.svg", import.meta.url).href,
  text: new URL("./icons/text.svg", import.meta.url).href,
  undo: new URL("./icons/undo.svg", import.meta.url).href,
  brush: new URL("./icons/brush.svg", import.meta.url).href,
  eraser: new URL("./icons/eraser.svg", import.meta.url).href,
  pencil: new URL("./icons/pencil.svg", import.meta.url).href,
  shapes: new URL("./icons/shapes.svg", import.meta.url).href,
  logo_brush: new URL("./icons/logo_brush.svg", import.meta.url).href,
  color_pellet: new URL("./icons/color_pellet.svg", import.meta.url).href,
};
